### ISSUE TITLE
MouseManager.cpp is not found

### ISSUE THREAD

**Issue by uzairrj** [pixelgriffin/OpenForager#1]
Hello,

The MouseManager.cpp is missing in the git repository. It raises compilation error. Please push the MouseManager.cpp. Thank You!

**Comment by pixelgriffin** [comment]
MouseManager.cpp implementation is intentionally missing to avoid people getting themselves banned with a public mouse movement script. Implement your own or simply print out the area to click.

**Comment by sc0rp10n-py** [comment]
Can you share example to MouseManager.cpp file?

**Comment by sc0rp10n-py** [comment]
@pixelgriffin or maybe share the public script too once?
